services:
  gaia-node:
    restart: unless-stopped
    hostname: gaia-node
    image: debian:bookworm-slim
    entrypoint: [ "sh", "-c", "chmod +x /docker-entrypoint-scripts.d/on-start.sh && /docker-entrypoint-scripts.d/on-start.sh" ]
    volumes:
      - ./on-start.sh:/docker-entrypoint-scripts.d/on-start.sh
      - ./init-chain.sh:/docker-entrypoint-scripts.d/init-chain.sh:ro
      - ./bin:/root/bin:ro
    
    environment:
      - CHAIN_ID=${CHAIN_ID:-gaia-local}
      - VALIDATOR_KEY=${VALIDATOR_KEY:-f9f762ae36cbbd1f56447893938a5a05103acf5bc8ff86ab89e780dc59df4c9a} # cosmos1s6prdpndfq2gpxx00pp95lqtm7kdwhrgsyyrl7
      # mnemonic for the relayer key below: (you'll need this for hermes)
      # voyage dust hand garlic fun trend bomb basic whisper mail camp egg basic normal dial crater prosper verb lyrics couch twenty matrix black example
      - RELAYER_KEY=${RELAYER_KEY:-a231fbc182e3d97586998e5d6c513742244a712cfccf70276851ea13898091ad} # cosmos16fzklxmtdf7p5396396226vrdcjpkf255cuxsf
      - FAUCET_KEY=${FAUCET_KEY:-a5e156429e5beefed5dec348026b02870fb0416f86a5c9e3bba1f7bd4dcaa6bc} # cosmos1fs6q65e95hmegp5nwjw59zu205y602jtcfjknw
    ports:
      - "${RPC_PORT:-27657}:26657"

volumes:
  gaia-data: