services:
  masp-postgres:
    image: postgres:16-alpine
    command: -c 'max_connections=200'
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_DB: masp_indexer_local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "masp_indexer_local"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 80s

  block-index:
    image: ghcr.io/anoma/namada-masp-indexer:block-index-builder-master
    build:
      context: .
      dockerfile: block-index/Dockerfile
    environment:
      COMETBFT_URL: ${COMETBFT_URL:-http://namada-node:26657}
      DATABASE_URL: postgres://postgres:password@masp-postgres:5432/masp_indexer_local
    depends_on:
      masp-postgres:
        condition: service_healthy

  masp-webserver:
    image: ghcr.io/anoma/namada-masp-indexer:webserver-master
    build:
      context: .
      dockerfile: webserver/Dockerfile
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      DATABASE_URL: postgres://postgres:password@masp-postgres:5432/masp_indexer_local
    depends_on:
      - crawler
  
  crawler:
    image: ghcr.io/anoma/namada-masp-indexer:chain-master
    build:
      context: .
      dockerfile: chain/Dockerfile
    environment:
      COMETBFT_URL: ${COMETBFT_URL:-http://namada-node:26657}
      DATABASE_URL: postgres://postgres:password@masp-postgres:5432/masp_indexer_local
    depends_on:
      masp-postgres:
        condition: service_healthy
