[[chains]]
id = 'CHAIN'
type = 'CosmosSdk'
rpc_addr = 'http://HOST:26657'
grpc_addr = 'http://HOST:9090'
event_source = { mode = 'push', url = 'ws://HOST:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '60s'
account_prefix = 'osmo'
key_name = 'KEY'
store_prefix = 'ibc'
default_gas = 5000000
max_gas = 15000000
gas_price = { price = 0.75, denom = 'DENOM' }
gas_multiplier = 4
max_msg_num = 30
max_tx_size = 800000
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '1days'
ccv_consumer_chain = false
sequential_batch_tx = false
memo_prefix = ''

[chains.packet_filter]
policy = 'allow'
list = [[
    'transfer',
    'channel-*',
]]

[chains.address_type]
derivation = 'cosmos'
